[package]
name = "pallet-template-rpc"
version = "2.0.0"
authors = ["JoshyOrndorff"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0" }
jsonrpc-core = "14.0.3"
jsonrpc-core-client = "14.0.3"
jsonrpc-derive = "14.0.3"
sp-core = { version = "2.0.0-rc4", path = "../../../../../primitives/core" }
sp-rpc = { version = "2.0.0-rc4", path = "../../../../../primitives/rpc" }
serde = { version = "1.0.101", features = ["derive"] }
sp-runtime = { version = "2.0.0-rc4", path = "../../../../../primitives/runtime" }
sp-blockchain = { version = "2.0.0-rc4", path = "../../../../../primitives/blockchain" }
sp-api = { version = "2.0.0-rc4", path = "../../../../../primitives/api" }

template-rpc-runtime-api = { version = "2.0.0-rc4", path = "./runtime-api" }
pallet-template = { version = "2.0.0-rc4", path = ".." }

[features]
default = ['std']
std = [
	"codec/std",
	"sp-core/std",
	"serde/std",
	"sp-runtime/std",
	"sp-api/std",
	"template-rpc-runtime-api/std",
	"pallet-template/std",
]
