[package]
name = "node-template"
version = "0.9.0"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"

[[bin]]
name = "template-node"
path = "src/main.rs"

[dependencies]
error-chain = "0.12"
futures = "0.1"
ctrlc = { version = "3.0", features = ["termination"] }
log = "0.4"
tokio = "0.1"
exit-future = "0.1"
parking_lot = "0.4"
hex-literal = "0.1"
slog = "^2"
parity-codec = "3.0"
trie-root = "0.9"
sr-io = { path = "../core/sr-io" }
substrate-cli = { path = "../core/cli" }
substrate-primitives = { path = "../core/primitives" }
substrate-executor = { path = "../core/executor" }
substrate-service = { path = "../core/service" }
substrate-inherents = { path = "../core/inherents" }
substrate-transaction-pool = { path = "../core/transaction-pool" }
substrate-network = { path = "../core/network" }
substrate-consensus-aura = { path = "../core/consensus/aura" }
substrate-client = {  path = "../core/client" }
substrate-basic-authorship = { path = "../core/basic-authorship" }
node-template-runtime = { path = "runtime" }
node-executor = { path = "../node/executor" }

[build-dependencies]
vergen = "3"

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
